const GERM_MARKETS = [
  // Tier 1 — Unmissable
  { name: "Nuremberg Christkindlesmarkt", flag: "🇩🇪", country: "Germany", city: "Nuremberg",
    lat: 49.4545, lng: 11.0775, region: "Germany & Austria classics",
    rank: 1, tier: 1, trip: "1 h by train",
    dates: "27 Nov – 24 Dec 2026", food: "Lebkuchen & Rostbratwürste",
    note: "The benchmark — five markets in one around the Main Market Square." },
  { name: "Rothenburg Reiterlesmarkt", flag: "🇩🇪", country: "Germany", city: "Rothenburg ob der Tauber",
    lat: 49.3748, lng: 10.1789, region: "Germany & Austria classics",
    rank: 2, tier: 1, trip: "2.5–3 h by train (overnight better)",
    dates: "27 Nov – 23 Dec 2026", food: "Schneeballen & Glühwein",
    note: "The most photogenic town in Germany — snow-dusted walls and half-timbered lanes." },
  { name: "Munich Christkindlmarkt Marienplatz", flag: "🇩🇪", country: "Germany", city: "Munich",
    lat: 48.1374, lng: 11.5755, region: "Germany & Austria classics",
    rank: 3, tier: 1, trip: "home turf",
    dates: "20 Nov – 24 Dec 2026", food: "Weisswurst & Feuerzangenbowle",
    note: "Plus Schwabing's medieval market, Tollwood and the Chinese Tower." },

  // Tier 2 — Worth a dedicated trip
  { name: "Regensburg Christkindlmarkt", flag: "🇩🇪", country: "Germany", city: "Regensburg",
    lat: 49.0195, lng: 12.0957, region: "Germany & Austria classics",
    rank: 4, tier: 2, trip: "< 1.5 h by train",
    dates: "early Dec – 23 Dec 2026", food: "Riebele & Fürstlicher Punsch",
    note: "UNESCO old town plus the 'romantic market' at Thurn und Taxis castle." },
  { name: "Augsburg Christkindlesmarkt", flag: "🇩🇪", country: "Germany", city: "Augsburg",
    lat: 48.3668, lng: 10.8988, region: "Germany & Austria classics",
    rank: 5, tier: 2, trip: "~40 min by train — easiest day trip",
    dates: "27 Nov – 24 Dec 2026", food: "Augsburger Zwetschgendatschi",
    note: "The Engelsspiel turns the Rathaus facade into a living Advent calendar." },
  { name: "Stuttgart Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Stuttgart",
    lat: 48.7784, lng: 9.1799, region: "Germany & Austria classics",
    rank: 6, tier: 2, trip: "~2.5 h by train",
    dates: "26 Nov – 23 Dec 2026", food: "Zimtsterne & Glühwein",
    note: "One of Europe's largest, with some of the best-decorated stalls." },
  { name: "Bamberg Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Bamberg",
    lat: 49.8935, lng: 10.8852, region: "Germany & Austria classics",
    rank: 7, tier: 2, trip: "~3 h by train (overnight better)",
    dates: "27 Nov – 23 Dec 2026", food: "Glühwein & Bamberger Hörnchen",
    note: "UNESCO river-island old town — quieter cousin of Nuremberg." },

  // Tier 3 — Great if nearby or for something quieter
  { name: "Würzburg Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Würzburg",
    lat: 49.7913, lng: 9.9534, region: "Germany & Austria classics",
    rank: 8, tier: 3, trip: "~2 h by train",
    dates: "25 Nov – 22 Dec 2026", food: "Franconian wine & Bratwurst",
    note: "Baroque Residenz backdrop; underrated, excellent wine stalls." },
  { name: "Ulm Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Ulm",
    lat: 48.3984, lng: 9.9900, region: "Germany & Austria classics",
    rank: 9, tier: 3, trip: "~2 h by train",
    dates: "late Nov – 23 Dec 2026", food: "Glühwein & Maultaschen",
    note: "Cozy market beneath the world's tallest church spire." },
  { name: "Heidelberg Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Heidelberg",
    lat: 49.4122, lng: 8.7100, region: "Germany & Austria classics",
    rank: 10, tier: 3, trip: "~3 h by train",
    dates: "24 Nov – 22 Dec 2026", food: "Glühwein & Bratwurst",
    note: "Spectacular castle-ruin backdrop, though busy with tour groups." },
  { name: "Freiburg Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Freiburg",
    lat: 47.9956, lng: 7.8524, region: "Germany & Austria classics",
    rank: 11, tier: 3, trip: "~4 h by train",
    dates: "late Nov – 23 Dec 2026", food: "Raclette & Glühwein",
    note: "Black Forest charm by the Münster, laid-back university vibe." },
  { name: "Tübingen Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Tübingen",
    lat: 48.5208, lng: 9.0559, region: "Germany & Austria classics",
    rank: 12, tier: 3, trip: "~3.5 h by train",
    dates: "early Dec – 22 Dec 2026", food: "Punsch & Maultaschen",
    note: "Riverside old town that feels genuinely local — a hidden gem." },
  { name: "Esslingen Mittelaltermarkt", flag: "🇩🇪", country: "Germany", city: "Esslingen",
    lat: 48.7400, lng: 9.3060, region: "Germany & Austria classics",
    rank: 13, tier: 3, trip: "~2.5 h by train",
    dates: "late Nov – 22 Dec 2026", food: "Met & Kässspätzle",
    note: "Medieval costumes and fire-jugglers — a different flavor entirely." },

  // Tier 4 — Niche / novelty add-ons
  { name: "Ravenna Gorge Market", flag: "🇩🇪", country: "Germany", city: "Ravenna Gorge",
    lat: 47.9070, lng: 8.1480, region: "Germany & Austria classics",
    rank: 14, tier: 4, trip: "~4 h by train",
    dates: "late Nov – 23 Dec 2026", food: "Glühwein & grilled cheese",
    note: "Stalls beneath a lit railway viaduct in the forest — unique but small." },
  { name: "Nördlingen Christkindlesmarkt", flag: "🇩🇪", country: "Germany", city: "Nördlingen",
    lat: 48.8518, lng: 10.4891, region: "Germany & Austria classics",
    rank: 15, tier: 4, trip: "~1.5 h by train",
    dates: "early Dec – 23 Dec 2026", food: "Glühwein & Bratwurst",
    note: "Walled town inside a meteor crater — charming but minor." },
  { name: "Lindau Christmas Market", flag: "🇩🇪", country: "Germany", city: "Lindau",
    lat: 47.5458, lng: 9.6840, region: "Germany & Austria classics",
    rank: 16, tier: 4, trip: "~2.5 h by train",
    dates: "early Dec – 23 Dec 2026", food: "Glühwein & fondue",
    note: "Lakeside island town on the Bodensee with Alpine views." },
  { name: "Chiemsee Advent (Prien)", flag: "🇩🇪", country: "Germany", city: "Prien am Chiemsee",
    lat: 47.8560, lng: 12.3450, region: "Germany & Austria classics",
    rank: 17, tier: 4, trip: "~1.5 h by train",
    dates: "Advent weekends, late Nov – 20 Dec 2026", food: "Glühwein & Dampfnudeln",
    note: "Cozy lakeside market facing the Alps; modest but scenic." }
];