const KMZ_MARKETS = [
  { name: "Marienplatz", flag: "🇩🇪", country: "Germany", city: "Munich", lat: 48.1373932, lng: 11.5754485, region: "KMZ · Munich", rank: 1, dates: "2026 season", food: "Glühwein & local treats", note: "Central Munich Christmas market." },
  { name: "Schwabinger Weihnachtsmarkt", flag: "🇩🇪", country: "Germany", city: "Munich", lat: 48.163206, lng: 11.5870477, region: "KMZ · Munich", rank: 2, dates: "2026 season", food: "Crafts & festive food", note: "Christmas market in Schwabing." },
  { name: "Sendlinger Tor", flag: "🇩🇪", country: "Germany", city: "Munich", lat: 48.1340387, lng: 11.5676369, region: "KMZ · Munich", rank: 3, dates: "2026 season", food: "Glühwein & snacks", note: "Market at Sendlinger Tor." },
  { name: "Tollwood Winterfestival", flag: "🇩🇪", country: "Germany", city: "Munich", lat: 48.1345084, lng: 11.5509707, region: "KMZ · Munich", rank: 4, dates: "2026 season", food: "International food", note: "Winter festival at the Theresienwiese." },
  { name: "Nürnberger Christkindlesmarkt", flag: "🇩🇪", country: "Germany", city: "Nuremberg", lat: 49.4540255, lng: 11.0772946, region: "KMZ · Germany", rank: 5, dates: "2026 season", food: "Lebkuchen & Rostbratwürste", note: "Nuremberg's famous Christkindlesmarkt." },
  { name: "Rothenburg ob der Tauber", flag: "🇩🇪", country: "Germany", city: "Rothenburg ob der Tauber", lat: 49.3801834, lng: 10.1867388, region: "KMZ · Germany", rank: 6, dates: "2026 season", food: "Schneeballen & mulled wine", note: "Storybook medieval town market." },
  { name: "Dresde", flag: "🇩🇪", country: "Germany", city: "Dresden", lat: 51.0504088, lng: 13.7372621, region: "KMZ · Germany", rank: 7, dates: "2026 season", food: "Christstollen & Glühwein", note: "Dresden Striezelmarkt." },
  { name: "Friburgo de Brisgovia", flag: "🇩🇪", country: "Germany", city: "Freiburg", lat: 47.9990077, lng: 7.8421043, region: "KMZ · Germany", rank: 8, dates: "2026 season", food: "Raclette & Glühwein", note: "Freiburg Christmas market." },
  { name: "Salzburgo", flag: "🇦🇹", country: "Austria", city: "Salzburg", lat: 47.8014154, lng: 13.0448441, region: "KMZ · Austria", rank: 9, dates: "2026 season", food: "Punsch & Mozartkugeln", note: "Salzburg Christkindlmarkt." },
  { name: "Innsbruck", flag: "🇦🇹", country: "Austria", city: "Innsbruck", lat: 47.2675322, lng: 11.3910349, region: "KMZ · Austria", rank: 10, dates: "2026 season", food: "Kiachln & Glühwein", note: "Alpine Christmas market." },
  { name: "Augsburgo", flag: "🇩🇪", country: "Germany", city: "Augsburg", lat: 48.3705449, lng: 10.89779, region: "KMZ · Germany", rank: 11, dates: "2026 season", food: "Zwetschgendatschi & Glühwein", note: "Augsburg Christkindlesmarkt." },
  { name: "Luxemburgo", flag: "🇱🇺", country: "Luxembourg", city: "Luxembourg", lat: 49.815273, lng: 6.129583, region: "KMZ · Luxembourg", rank: 12, dates: "2026 season", food: "Gromperekichelcher & wine", note: "Luxembourg City winter market." },
  { name: "Weihnachtsmarkt Ravennaschlucht", flag: "🇩🇪", country: "Germany", city: "Ravenna Gorge", lat: 47.917253, lng: 8.0741509, region: "KMZ · Germany", rank: 13, dates: "2026 season", food: "Glühwein & grilled cheese", note: "Market beneath the railway viaduct." },
  { name: "Wiesbaden", flag: "🇩🇪", country: "Germany", city: "Wiesbaden", lat: 50.0716207, lng: 8.2448344, region: "KMZ · Germany", rank: 14, dates: "2026 season", food: "Glühwein & festive snacks", note: "Wiesbaden Christmas market." },
  { name: "Bamberg", flag: "🇩🇪", country: "Germany", city: "Bamberg", lat: 49.8988135, lng: 10.9027636, region: "KMZ · Germany", rank: 15, dates: "2026 season", food: "Glühwein & Bamberger Hörnchen", note: "Bamberg Christmas market." },
  { name: "Český Krumlov", flag: "🇨🇿", country: "Czechia", city: "Český Krumlov", lat: 48.8127354, lng: 14.3174657, region: "KMZ · Czechia", rank: 16, dates: "2026 season", food: "Trdelník & mulled wine", note: "Christmas market in the historic old town." },
  { name: "Bolzano", flag: "🇮🇹", country: "Italy", city: "Bolzano", lat: 46.4949259, lng: 11.3402543, region: "KMZ · Italy", rank: 17, dates: "2026 season", food: "Vin brulé & South Tyrolean treats", note: "Bolzano Christmas market." }
];
