const MARKETS = [
  // ── Germany & Austria classics ─────────────────────────────────────────
  { name: "Nuremberg Christkindlesmarkt",
    rank: 2, flag: "🇩🇪", country: "Germany", city: "Nuremberg",
    lat: 49.4545, lng: 11.0775, region: "Germany & Austria classics",
    dates: "27 Nov – 24 Dec 2026", food: "Lebkuchen & Rostbratwürste",
    note: "Germany's most famous market, opens with the Christkind prologue." },
  { name: "Dresden Striezelmarkt",
    rank: 4, flag: "🇩🇪", country: "Germany", city: "Dresden",
    lat: 51.0491, lng: 13.7392, region: "Germany & Austria classics",
    dates: "25 Nov – 24 Dec 2026", food: "Dresdner Christstollen",
    note: "Oldest documented market in Europe (since 1434)." },
  { name: "Cologne Cathedral Market",
    rank: 5, flag: "🇩🇪", country: "Germany", city: "Cologne",
    lat: 50.9413, lng: 6.9581, region: "Germany & Austria classics",
    dates: "23 Nov – 23 Dec 2026", food: "Reibekuchen & Glühwein",
    note: "One of 6–7 themed markets beneath the great Dom." },
  { name: "Vienna Rathausplatz",
    rank: 3, flag: "🇦🇹", country: "Austria", city: "Vienna",
    lat: 48.2104, lng: 16.3566, region: "Germany & Austria classics",
    dates: "13 Nov – 26 Dec 2026", food: "Punsch & roast chestnuts",
    note: "One of Europe's largest, with the 'Ice Dream' rink." },
  { name: "Salzburg Christkindlmarkt",
    rank: 6, flag: "🇦🇹", country: "Austria", city: "Salzburg",
    lat: 47.7980, lng: 13.0464, region: "Germany & Austria classics",
    dates: "20 Nov – 26 Dec 2026", food: "Glühwein & Mozartkugeln",
    note: "Baroque cathedral backdrop, famous carol concerts." },
  { name: "Innsbruck Christkindlmarkt",
    rank: 12, flag: "🇦🇹", country: "Austria", city: "Innsbruck",
    lat: 47.2679, lng: 11.3910, region: "Germany & Austria classics",
    dates: "15 Nov – 23 Dec 2026", food: "Kiachln & Glühwein",
    note: "Snow-dusted Alpine old town with mountain views." },
  { name: "Munich Christkindlmarkt Marienplatz",
    rank: 7, flag: "🇩🇪", country: "Germany", city: "Munich",
    lat: 48.1374, lng: 11.5755, region: "Germany & Austria classics",
    dates: "27 Nov – 24 Dec 2026", food: "Weisswurst & Feuerzangenbowle",
    note: "Iconic market under the Gothic Neues Rathaus tower." },
  { name: "Berlin Gendarmenmarkt",
    rank: 19, flag: "🇩🇪", country: "Germany", city: "Berlin",
    lat: 52.5137, lng: 13.3927, region: "Germany & Austria classics",
    dates: "24 Nov – 31 Dec 2026", food: "Stollen & hot mead",
    note: "Often voted one of Germany's most beautiful, framed by twin cathedrals." },
  { name: "Stuttgart Weihnachtsmarkt",
    rank: 57, flag: "🇩🇪", country: "Germany", city: "Stuttgart",
    lat: 48.7784, lng: 9.1799, region: "Germany & Austria classics",
    dates: "26 Nov – 23 Dec 2026", food: "Zimtsterne & Glühwein",
    note: "~300 stalls in the old town; one of Germany's biggest." },
  { name: "Hamburg Rathausmarkt",
    rank: 56, flag: "🇩🇪", country: "Germany", city: "Hamburg",
    lat: 53.5504, lng: 9.9937, region: "Germany & Austria classics",
    dates: "24 Nov – 23 Dec 2026", food: "Friese Labskaus & Glühwein",
    note: "Festive square before the grand town hall, plus a maritime market nearby." },
  { name: "Frankfurt Römerberg",
    rank: 28, flag: "🇩🇪", country: "Germany", city: "Frankfurt",
    lat: 50.1109, lng: 8.6821, region: "Germany & Austria classics",
    dates: "25 Nov – 22 Dec 2026", food: "Bethmännchen & Apfelwein punch",
    note: "Half-timbered Römer square; a giant nostalgic 'Frankfurter Markt'." },
  { name: "Leipzig Weihnachtsmarkt",
    rank: 29, flag: "🇩🇪", country: "Germany", city: "Leipzig",
    lat: 51.3400, lng: 12.3750, region: "Germany & Austria classics",
    dates: "24 Nov – 23 Dec 2026", food: "Quarkkeulchen & Glühwein",
    note: "One of Germany's oldest, with the world's tallest walkable Christmas pyramid." },
  { name: "Rothenburg ob der Tauber",
    rank: 10, flag: "🇩🇪", country: "Germany", city: "Rothenburg ob der Tauber",
    lat: 49.3748, lng: 10.1789, region: "Germany & Austria classics",
    dates: "27 Nov – 23 Dec 2026", food: "Schneeballen & mulled wine",
    note: "Medieval walled town; 'Reiterlesmarkt' is pure storybook." },
  { name: "Aachen Christkindchenmarkt",
    rank: 31, flag: "🇩🇪", country: "Germany", city: "Aachen",
    lat: 50.7757, lng: 6.0839, region: "Germany & Austria classics",
    dates: "20 Nov – 23 Dec 2026", food: "Aachener Printen & Glühwein",
    note: "Thousands of candles light the Rathaus square each Friday." },
  { name: "Heidelberg Weihnachtsmarkt",
    rank: 58, flag: "🇩🇪", country: "Germany", city: "Heidelberg",
    lat: 49.4122, lng: 8.7100, region: "Germany & Austria classics",
    dates: "24 Nov – 22 Dec 2026", food: "Glühwein & Bratwurst",
    note: "Twinkling markets along the old town under a castle." },
  { name: "Augsburg Christkindlesmarkt",
    rank: 59, flag: "🇩🇪", country: "Germany", city: "Augsburg",
    lat: 48.3668, lng: 10.8988, region: "Germany & Austria classics",
    dates: "27 Nov – 24 Dec 2026", food: "Augsburger Zwetschgendatschi",
    note: "One of Germany's oldest, at the Renaissance Rathausplatz." },
  { name: "Erfurt Weihnachtsmarkt",
    rank: 30, flag: "🇩🇪", country: "Germany", city: "Erfurt",
    lat: 50.9781, lng: 11.0281, region: "Germany & Austria classics",
    dates: "25 Nov – 23 Dec 2026", food: "Thuringian Bratwurst & Glühwein",
    note: "Runs across the cathedral square; medieval charm." },
  { name: "Linz Christkindlmarkt",
    rank: 60, flag: "🇦🇹", country: "Austria", city: "Linz",
    lat: 48.3069, lng: 14.2858, region: "Germany & Austria classics",
    dates: "20 Nov – 24 Dec 2026", food: "Lebkuchen & Punsch",
    note: "Main square market plus krampus parades." },
  { name: "Graz Adventmarkt",
    rank: 42, flag: "🇦🇹", country: "Austria", city: "Graz",
    lat: 47.0707, lng: 15.4395, region: "Germany & Austria classics",
    dates: "25 Nov – 24 Dec 2026", food: "Kastanien & Glühmost",
    note: "Austria's second city with a lively Schlossberg backdrop." },

  // ── France & Alsace ─────────────────────────────────────────────────────
  { name: "Strasbourg — Capital of Christmas",
    rank: 1, flag: "🇫🇷", country: "France", city: "Strasbourg",
    lat: 48.5836, lng: 7.7462, region: "France & Alsace",
    dates: "27 Nov – 24 Dec 2026", food: "Vin chaud & Bredele",
    note: "Oldest French market (since 1570); giant tree on Place Kléber." },
  { name: "Colmar Marché de Noël",
    rank: 25, flag: "🇫🇷", country: "France", city: "Colmar",
    lat: 48.0793, lng: 7.3585, region: "France & Alsace",
    dates: "25 Nov – 29 Dec 2026", food: "Berawecka & Alsatian wine",
    note: "Six fairy-tale markets in a half-timbered old town." },
  { name: "Paris — La Défense",
    rank: 88, flag: "🇫🇷", country: "France", city: "Paris",
    lat: 48.8924, lng: 2.2352, region: "France & Alsace",
    dates: "12 Nov 2026 – 3 Jan 2027", food: "Raclette & vin chaud",
    note: "Biggest market in Paris with 300+ stalls." },
  { name: "Paris — Notre-Dame",
    rank: 89, flag: "🇫🇷", country: "France", city: "Paris",
    lat: 48.8530, lng: 2.3499, region: "France & Alsace",
    dates: "26 Nov – 27 Dec 2026", food: "Oysters & mulled wine",
    note: "Elegant artisan boutiques along the Seine." },
  { name: "Paris — Tuileries Garden",
    rank: 20, flag: "🇫🇷", country: "France", city: "Paris",
    lat: 48.8630, lng: 2.3265, region: "France & Alsace",
    dates: "mid Nov 2026 – early Jan 2027", food: "Tartiflette & churros",
    note: "La Magie de Noël: fair rides, food hall, chalets." },
  { name: "Lille Grand-Place",
    rank: 52, flag: "🇫🇷", country: "France", city: "Lille",
    lat: 50.6366, lng: 3.0635, region: "France & Alsace",
    dates: "late Nov – 31 Dec 2026", food: "Welsh au Maroilles & vin chaud",
    note: "Northern France's grand Christmas village and big wheel." },
  { name: "Montbéliard Noël",
    rank: 87, flag: "🇫🇷", country: "France", city: "Montbéliard",
    lat: 47.5100, lng: 6.7980, region: "France & Alsace",
    dates: "late Nov – 24 Dec 2026", food: "Cancoillotte & mulled wine",
    note: "Rivals Strasbourg; 100+ chalets in the old town." },
  { name: "Mulhouse Marché de Noël",
    rank: 61, flag: "🇫🇷", country: "France", city: "Mulhouse",
    lat: 47.7480, lng: 7.3390, region: "France & Alsace",
    dates: "late Nov – 24 Dec 2026", food: "Bretzel & vin chaud",
    note: "Alsace's second market; giant moving street-art displays." },
  { name: "Metz Marché de Noël",
    rank: 22, flag: "🇫🇷", country: "France", city: "Metz",
    lat: 49.1193, lng: 6.1757, region: "France & Alsace",
    dates: "mid Nov – 31 Dec 2026", food: "Mirabelle tarts & vin chaud",
    note: "Light projections on the Gothic Saint-Étienne cathedral." },
  { name: "Nancy Marché de Noël",
    rank: 62, flag: "🇫🇷", country: "France", city: "Nancy",
    lat: 48.6921, lng: 6.1844, region: "France & Alsace",
    dates: "late Nov – 30 Dec 2026", food: "Bergamotes de Nancy & vin chaud",
    note: "Market steps onto the UNESCO Place Stanislas." },
  { name: "Lyon — Fête des Lumières Market",
    rank: 63, flag: "🇫🇷", country: "France", city: "Lyon",
    lat: 45.7578, lng: 4.8320, region: "France & Alsace",
    dates: "early Dec – 24 Dec 2026", food: "Vin chaud & saucisson",
    note: "Combines market with the famous Festival of Lights." },
  { name: "Annecy Noël",
    rank: 51, flag: "🇫🇷", country: "France", city: "Annecy",
    lat: 45.8992, lng: 6.1294, region: "France & Alsace",
    dates: "late Nov – 24 Dec 2026", food: "Beaufort fondue & vin chaud",
    note: "Venetian-style market beside the frozen lake." },
  { name: "Reims Marché de Noël",
    rank: 53, flag: "🇫🇷", country: "France", city: "Reims",
    lat: 49.2583, lng: 4.0317, region: "France & Alsace",
    dates: "late Nov – 30 Dec 2026", food: "Champagne & brioche",
    note: "Chalets at the foot of Notre-Dame cathedral." },

  // ── Eastern Europe ─────────────────────────────────────────────────────
  { name: "Prague Old Town Square",
    rank: 8, flag: "🇨🇿", country: "Czech Republic", city: "Prague",
    lat: 50.0875, lng: 14.4213, region: "Eastern Europe",
    dates: "28 Nov – 6 Jan 2027", food: "Trdelník & mulled wine",
    note: "Gothic fairy-tale square, giant tree and carol stage." },
  { name: "Kraków Rynek Główny",
    rank: 18, flag: "🇵🇱", country: "Poland", city: "Kraków",
    lat: 50.0617, lng: 19.9373, region: "Eastern Europe",
    dates: "28 Nov – 1 Jan 2027", food: "Oscypek smoked cheese",
    note: "Europe's largest medieval square, beside the Cloth Hall." },
  { name: "Budapest Basilica Market",
    rank: 9, flag: "🇭🇺", country: "Hungary", city: "Budapest",
    lat: 47.5005, lng: 19.0535, region: "Eastern Europe",
    dates: "mid Nov – 1 Jan 2027", food: "Kürtőskalács chimney cake",
    note: "Light show on St Stephen's Basilica, folk crafts." },
  { name: "Tallinn Town Hall Square",
    rank: 17, flag: "🇪🇪", country: "Estonia", city: "Tallinn",
    lat: 59.4370, lng: 24.7454, region: "Eastern Europe",
    dates: "20 Nov – 6 Jan 2027", food: "Hõõgvein & blood sausage",
    note: "Medieval square, one of Europe's first public Christmas trees." },
  { name: "Zagreb Advent",
    rank: 26, flag: "🇭🇷", country: "Croatia", city: "Zagreb",
    lat: 45.8131, lng: 15.9775, region: "Eastern Europe",
    dates: "early Dec – 7 Jan 2027", food: "Kuhano vino & fritule",
    note: "Repeatedly voted Europe's Best Christmas Market." },
  { name: "Ljubljana Christmas Market",
    rank: 27, flag: "🇸🇮", country: "Slovenia", city: "Ljubljana",
    lat: 46.0514, lng: 14.5060, region: "Eastern Europe",
    dates: "early Dec – early Jan 2027", food: "Pogača & mulled wine",
    note: "Cute waterfront chalets along the Ljubljanica river." },
  { name: "Riga Christmas Market",
    rank: 33, flag: "🇱🇻", country: "Latvia", city: "Riga",
    lat: 56.9475, lng: 24.1064, region: "Eastern Europe",
    dates: "1 Dec – 6 Jan 2027", food: "Piparkūkas & honey wine",
    note: "Home of what's often called the first Christmas tree." },
  { name: "Vilnius Christmas Market",
    rank: 34, flag: "🇱🇹", country: "Lithuania", city: "Vilnius",
    lat: 54.6872, lng: 25.2797, region: "Eastern Europe",
    dates: "early Dec – early Jan 2027", food: "Šakotis & mulled wine",
    note: "Baroque old town glows with lights each December." },
  { name: "Bratislava Hlavné námestie",
    rank: 21, flag: "🇸🇰", country: "Slovakia", city: "Bratislava",
    lat: 48.1436, lng: 17.1083, region: "Eastern Europe",
    dates: "20 Nov – 22 Dec 2026", food: "Medovina & bratislava rolls",
    note: "Twin squares (Hlavné + Františkánske) under the castle." },
  { name: "Wrocław Christmas Market",
    rank: 65, flag: "🇵🇱", country: "Poland", city: "Wrocław",
    lat: 51.1079, lng: 17.0305, region: "Eastern Europe",
    dates: "late Nov – 6 Jan 2027", food: "Pierogi & grzaniec",
    note: "Market on the historic Rynek with gnomes everywhere." },
  { name: "Gdańsk Jarmark Bożonarodzeniowy",
    rank: 66, flag: "🇵🇱", country: "Poland", city: "Gdańsk",
    lat: 54.3520, lng: 18.6466, region: "Eastern Europe",
    dates: "late Nov – 31 Dec 2026", food: "Oscypek & mulled beer",
    note: "Maritime market on the golden Motława waterfront." },
  { name: "Warsaw Christmas Market",
    rank: 67, flag: "🇵🇱", country: "Poland", city: "Warsaw",
    lat: 52.2322, lng: 21.0080, region: "Eastern Europe",
    dates: "early Dec – early Jan 2027", food: "Pierogi & hot chocolate",
    note: "Market on the Old Town Market Square and along Krakowskie." },
  { name: "Cluj-Napoca Christmas Market",
    rank: 68, flag: "🇷🇴", country: "Romania", city: "Cluj-Napoca",
    lat: 46.7712, lng: 23.6236, region: "Eastern Europe",
    dates: "Dec 2026 (TBC)", food: "Langos & vin fiert",
    note: "Award-winning market in Transylvania's heart." },
  { name: "Sibiu Christmas Market",
    rank: 69, flag: "🇷🇴", country: "Romania", city: "Sibiu",
    lat: 45.7966, lng: 24.1494, region: "Eastern Europe",
    dates: "Dec 2026 (TBC)", food: "Sarmale & mulled wine",
    note: "Set in Piata Mare with nod to the old Christmas markets." },
  { name: "Belgrade Christmas Market",
    rank: 70, flag: "🇷🇸", country: "Serbia", city: "Belgrade",
    lat: 44.8176, lng: 20.4569, region: "Eastern Europe",
    dates: "Dec 2026 – early Jan 2027 (TBC)", food: "Kuvano vino & kiflice",
    note: "Fairy-tale houses on Trg Republike." },
  { name: "Sofia Christmas Market",
    rank: 71, flag: "🇧🇬", country: "Bulgaria", city: "Sofia",
    lat: 42.6977, lng: 23.3219, region: "Eastern Europe",
    dates: "Dec 2026 – early Jan 2027 (TBC)", food: "Banitsa & hot wine",
    note: "Chalet avenue in front of the National Theatre." },
  { name: "Kaunas Christmas Market",
    rank: 72, flag: "🇱🇹", country: "Lithuania", city: "Kaunas",
    lat: 54.8972, lng: 23.8860, region: "Eastern Europe",
    dates: "Dec 2026 (TBC)", food: "Kūčiukai & mulled wine",
    note: "Art Deco town hall lit like a giant advent calendar." },
  { name: "Brno Christmas Market",
    rank: 73, flag: "🇨🇿", country: "Czech Republic", city: "Brno",
    lat: 49.1951, lng: 16.6068, region: "Eastern Europe",
    dates: "mid Nov – 24 Dec 2026", food: "Trdelník & medovina",
    note: "Three squares of stalls under the Špilberk castle." },
  { name: "Český Krumlov Advent",
    rank: 74, flag: "🇨🇿", country: "Czech Republic", city: "Český Krumlov",
    lat: 48.8103, lng: 14.3150, region: "Eastern Europe",
    dates: "late Nov – 24 Dec 2026", food: "Trdelník & mulled wine",
    note: "Festive chalets in a storybook castle town." },

  // ── Nordic & Benelux ────────────────────────────────────────────────────
  { name: "Copenhagen Tivoli Gardens",
    rank: 16, flag: "🇩🇰", country: "Denmark", city: "Copenhagen",
    lat: 55.6735, lng: 12.5664, region: "Nordic & Benelux",
    dates: "mid Nov – early Jan 2027", food: "Gløgg & æbleskiver",
    note: "Historic amusement park in Nordic winter lights (ticket)." },
  { name: "Brussels Winter Wonders",
    rank: 11, flag: "🇧🇪", country: "Belgium", city: "Brussels",
    lat: 50.8467, lng: 4.3525, region: "Nordic & Benelux",
    dates: "27 Nov – 3 Jan 2027", food: "Belgian chocolate & Glühwein",
    note: "250+ chalets around the gilded Grand Place." },
  { name: "Bruges Winter Glow",
    rank: 14, flag: "🇧🇪", country: "Belgium", city: "Bruges",
    lat: 51.2086, lng: 3.2267, region: "Nordic & Benelux",
    dates: "20 Nov – 3 Jan 2027", food: "Waffles & hot chocolate",
    note: "Medieval canals lit by a light trail and ice rink." },
  { name: "Stockholm Stortorget",
    rank: 35, flag: "🇸🇪", country: "Sweden", city: "Stockholm",
    lat: 59.3251, lng: 18.0712, region: "Nordic & Benelux",
    dates: "mid Nov – 23 Dec 2026", food: "Glögg & pepparkakor",
    note: "Gamla Stan's oldest market among medieval facades." },
  { name: "Gothenburg Liseberg",
    rank: 15, flag: "🇸🇪", country: "Sweden", city: "Gothenburg",
    lat: 57.7089, lng: 11.9746, region: "Nordic & Benelux",
    dates: "mid Nov – Dec 2026 (TBC)", food: "Glögg & semlor",
    note: "Amusement park transformed into a winter wonderland." },
  { name: "Oslo Christmas Market",
    rank: 75, flag: "🇳🇴", country: "Norway", city: "Oslo",
    lat: 59.9127, lng: 10.7461, region: "Nordic & Benelux",
    dates: "mid Nov – 22 Dec 2026", food: "Gløgg & pinnekjøtt bite",
    note: "Stalls at the Spikersuppa rink opposite the Royal Palace." },
  { name: "Helsinki Tuomaan Markkinat",
    rank: 76, flag: "🇫🇮", country: "Finland", city: "Helsinki",
    lat: 60.1699, lng: 24.9523, region: "Nordic & Benelux",
    dates: "early Dec – 22 Dec 2026", food: "Glögi & karjalanpiirakka",
    note: "St. Thomas market on the snowy Senate Square." },
  { name: "Turku Christmas Market",
    rank: 77, flag: "🇫🇮", country: "Finland", city: "Turku",
    lat: 60.4518, lng: 22.2666, region: "Nordic & Benelux",
    dates: "Dec 2026 (TBC)", food: "Joulutorttu & glögi",
    note: "Finland's official Christmas City; peace declaration at noon." },
  { name: "Rovaniemi Arctic Circle",
    rank: 55, flag: "🇫🇮", country: "Finland", city: "Rovaniemi",
    lat: 66.5039, lng: 25.7294, region: "Nordic & Benelux",
    dates: "Dec 2026 – early Jan 2027 (TBC)", food: "Poronkäristys & glögi",
    note: "Santa Claus Village — Christmas all year plus auroras." },
  { name: "Reykjavik Christmas Market",
    rank: 79, flag: "🇮🇸", country: "Iceland", city: "Reykjavik",
    lat: 64.1466, lng: -21.9426, region: "Nordic & Benelux",
    dates: "Dec 2026 (TBC)", food: "Kleina & heißer Kakao",
    note: "Nordic craft market; 13 Yule Lads folklore." },
  { name: "London Winter Wonderland",
    rank: 90, flag: "🇬🇧", country: "UK", city: "London",
    lat: 51.5074, lng: -0.1657, region: "Nordic & Benelux",
    dates: "19 Nov 2026 – 3 Jan 2027", food: "Bratwurst & hot chocolate",
    note: "Hyde Park's giant festive fair with market, ice rink and circus." },
  { name: "Edinburgh Christmas Market",
    rank: 36, flag: "🇬🇧", country: "UK", city: "Edinburgh",
    lat: 55.9533, lng: -3.2002, region: "Nordic & Benelux",
    dates: "mid Nov – early Jan 2027", food: "Mulled wine & roast chestnuts",
    note: "Princes Street Gardens beneath an illuminated castle." },
  { name: "Manchester Christmas Markets",
    rank: 38, flag: "🇬🇧", country: "UK", city: "Manchester",
    lat: 53.4808, lng: -2.2426, region: "Nordic & Benelux",
    dates: "mid Nov – 21 Dec 2026", food: "German bratwurst & mulled cider",
    note: "UK's most famous spread of wooden chalets across the city." },
  { name: "Birmingham Frankfurt Market",
    rank: 80, flag: "🇬🇧", country: "UK", city: "Birmingham",
    lat: 52.4797, lng: -1.9027, region: "Nordic & Benelux",
    dates: "mid Nov – 23 Dec 2026", food: "Bratwurst & Glühwein",
    note: "The UK's largest authentic German Christmas market." },
  { name: "Amsterdam Winter Paradise",
    rank: 41, flag: "🇳🇱", country: "Netherlands", city: "Amsterdam",
    lat: 52.3663, lng: 4.8964, region: "Nordic & Benelux",
    dates: "3 – 27 Dec 2026", food: "Oliebollen & goulash soup",
    note: "Rembrandtplein's open-air market amidst canal lights." },
  { name: "Antwerp Grote Markt",
    rank: 64, flag: "🇧🇪", country: "Belgium", city: "Antwerp",
    lat: 51.2213, lng: 4.3997, region: "Nordic & Benelux",
    dates: "Dec 2026 – early Jan 2027 (TBC)", food: "Warme wafels & Glühwein",
    note: "Winter in Antwerp: ice rink and chalets by the cathedral." },
  { name: "Basel Basler Weihnachtsmarkt",
    rank: 13, flag: "🇨🇭", country: "Switzerland", city: "Basel",
    lat: 47.5596, lng: 7.5886, region: "Nordic & Benelux",
    dates: "late Nov – 23 Dec 2026", food: "Basler Läckerli & Glühwein",
    note: "Two of Switzerland's loveliest squares (Barfüsser, Münster)." },
  { name: "Zurich Streifzug",
    rank: 49, flag: "🇨🇭", country: "Switzerland", city: "Zurich",
    lat: 47.3769, lng: 8.5417, region: "Nordic & Benelux",
    dates: "mid Nov – 24 Dec 2026", food: "Raclette & Glühwein",
    note: "Chalets through the old town plus a giant fir in Bahnhofstrasse." },
  { name: "Luxembourg City Winterlights",
    rank: 81, flag: "🇱🇺", country: "Luxembourg", city: "Luxembourg",
    lat: 49.6097, lng: 6.1264, region: "Nordic & Benelux",
    dates: "mid Nov – early Jan 2027 (TBC)", food: "White wine & Gromperekichelcher",
    note: "Chalets and light trail between the Old Town and Grund." },
  { name: "Bergen Christmas Market",
    rank: 78, flag: "🇳🇴", country: "Norway", city: "Bergen",
    lat: 60.3913, lng: 5.3221, region: "Nordic & Benelux",
    dates: "late Nov – 23 Dec 2026", food: "Gløgg & lutefisk",
    note: "Fjord-side market by the Hanseatic Bryggen wharf." },

  // ── Extra: UK, Benelux & France (from travel shortlist) ───────────────
  { name: "Leuven Christmas Market",
    rank: 32, flag: "🇧🇪", country: "Belgium", city: "Leuven",
    lat: 50.8792, lng: 4.7010, region: "Nordic & Benelux",
    dates: "Dec 2026 (TBC)", food: "Glühwein & waffles",
    note: "Compact market before the Gothic town hall." },
  { name: "Bath Christmas Market",
    rank: 37, flag: "🇬🇧", country: "UK", city: "Bath",
    lat: 51.3811, lng: -2.3590, region: "Nordic & Benelux",
    dates: "late Nov – 28 Dec 2026", food: "Mulled cider & mince pies",
    note: "Georgian streets and the Abbey framed by 170 huts." },
  { name: "Blenheim Palace Market",
    rank: 39, flag: "🇬🇧", country: "UK", city: "Woodstock",
    lat: 51.8414, lng: -1.3605, region: "Nordic & Benelux",
    dates: "Nov – early Jan 2027 (TBC)", food: "Hot chocolate & bratwurst",
    note: "Spectacular illuminated palace courtyard setting." },
  { name: "Valkenburg Christmas Market",
    rank: 40, flag: "🇳🇱", country: "Netherlands", city: "Valkenburg",
    lat: 50.8646, lng: 5.8306, region: "Nordic & Benelux",
    dates: "mid Nov – Dec 2026 (TBC)", food: "Oliebollen & Glühwein",
    note: "South Limburg's underground 'cave markets' — a rarity." },
  { name: "Amiens Marché de Noël",
    rank: 54, flag: "🇫🇷", country: "France", city: "Amiens",
    lat: 49.8941, lng: 2.3028, region: "France & Alsace",
    dates: "late Nov – 31 Dec 2026", food: "Vin chaud & ch'ti waffles",
    note: "One of France's biggest markets, at the Gothic cathedral." },

  // ── Extra: Germany (from the German shortlist) ─────────────────────────
  { name: "Regensburg Christkindlmarkt",
    rank: 82, flag: "🇩🇪", country: "Germany", city: "Regensburg",
    lat: 49.0195, lng: 12.0957, region: "Germany & Austria classics",
    dates: "early Dec – 23 Dec 2026", food: "Riebele & Glühwein",
    note: "Four markets across a beautiful medieval Danube old town." },
  { name: "Esslingen Mittelaltermarkt",
    rank: 83, flag: "🇩🇪", country: "Germany", city: "Esslingen",
    lat: 48.7400, lng: 9.3060, region: "Germany & Austria classics",
    dates: "late Nov – 22 Dec 2026", food: "Met & Schwäbische Kässpätzle",
    note: "Germany's biggest medieval-themed market, minstrels and all." },
  { name: "Ravenna Gorge Market",
    rank: 84, flag: "🇩🇪", country: "Germany", city: "Hinterzarten",
    lat: 47.9070, lng: 8.1480, region: "Germany & Austria classics",
    dates: "late Nov – 23 Dec 2026", food: "Glühwein & grilled cheese",
    note: "Fairy-tale chalets under a snowbound railway viaduct." },
  { name: "Bamberg Weihnachtsmarkt",
    rank: 85, flag: "🇩🇪", country: "Germany", city: "Bamberg",
    lat: 49.8935, lng: 10.8852, region: "Germany & Austria classics",
    dates: "27 Nov – 23 Dec 2026", food: "Bamberger Hörnchen & Glühwein",
    note: "Markets on Maxplatz and green Coburg Square, UNESCO town." },
  { name: "Goslar Weihnachtsmarkt",
    rank: 86, flag: "🇩🇪", country: "Germany", city: "Goslar",
    lat: 51.9059, lng: 10.4290, region: "Germany & Austria classics",
    dates: "early Dec – 23 Dec 2026", food: "Glühwein & Sauerbraten",
    note: "Medieval imperial town under the Harz mountains." },

  // ── Extra: Italy & the Alps ────────────────────────────────────────────
  { name: "Bolzano Christkindlmarkt",
    rank: 43, flag: "🇮🇹", country: "Italy", city: "Bolzano",
    lat: 46.4983, lng: 11.3548, region: "Italy & Alps",
    dates: "early Dec – 6 Jan 2027", food: "Zelten & vin brulé",
    note: "South Tyrol's original market on Piazza Walther." },
  { name: "Merano Christmas Market",
    rank: 44, flag: "🇮🇹", country: "Italy", city: "Merano",
    lat: 46.6720, lng: 11.1590, region: "Italy & Alps",
    dates: "late Nov – 6 Jan 2027", food: "Krapfen & vin brulé",
    note: "Belle-époque spa town wrapped in Alpine lights." },
  { name: "Bressanone (Brixen) Market",
    rank: 45, flag: "🇮🇹", country: "Italy", city: "Bressanone",
    lat: 46.7167, lng: 11.6576, region: "Italy & Alps",
    dates: "early Dec – 6 Jan 2027", food: "Apple strudel & vin brulé",
    note: "Small alpine Rome, Italy's oldest bishopric town." },
  { name: "Trento Market",
    rank: 46, flag: "🇮🇹", country: "Italy", city: "Trento",
    lat: 46.0667, lng: 11.1191, region: "Italy & Alps",
    dates: "late Nov – 6 Jan 2027", food: "Torrone & vin brulé",
    note: "Market across Piazza Fiera against the Dolomite skyline." },
  { name: "Lucerne Christkindlimärt",
    rank: 47, flag: "🇨🇭", country: "Switzerland", city: "Lucerne",
    lat: 47.0502, lng: 8.3093, region: "Nordic & Benelux",
    dates: "late Nov – 24 Dec 2026", food: "Raclette & Glühwein",
    note: "Alpine-town market beneath the wooden Kapellbrücke." },
  { name: "Montreux Noël",
    rank: 48, flag: "🇨🇭", country: "Switzerland", city: "Montreux",
    lat: 46.4310, lng: 6.9128, region: "Nordic & Benelux",
    dates: "20 Nov – 24 Dec 2026", food: "Raclette & fondue",
    note: "Lakefront market with Santa's nightly sleigh 'flights'." },
  { name: "Bern Christmas Market",
    rank: 50, flag: "🇨🇭", country: "Switzerland", city: "Bern",
    lat: 46.9480, lng: 7.4474, region: "Nordic & Benelux",
    dates: "late Nov – 24 Dec 2026", food: "Bernese honey gingerbread & Glühwein",
    note: "Arcaded historic centre with the world's largest Advent window." },

  // ── Extra: from the latest ranking ─────────────────────────────────────
  { name: "Ghent Winter Market",
    rank: 23, flag: "🇧🇪", country: "Belgium", city: "Ghent",
    lat: 51.0543, lng: 3.7250, region: "Nordic & Benelux",
    dates: "Dec 2026 (TBC)", food: "Glühwein & cuberdons",
    note: "Charming canal-side setting; smaller and quieter than Bruges." },
];